### ISSUE TITLE
API /rock/:id 

### ISSUE THREAD

**Issue by mr-eggleton** [UTCSheffield/rockstarapi#1]
GET retrieves from the datastore the code and cached data 
POST stores the code runs it (caches if successful) returns 
PUT updates and reruns the code changing the cache if successful

Do we update the rock if the code fails ????

**Comment by mr-eggleton** [comment]
Same return type for all calls:
```json
{
    "id" : 45678,
    "status" : "success",
    "code" : "lots of stuff\nwith lots of lines",
    "data" : { 
        "name"  : [2,45,463,64,245,325,325,243], 
        "name2" : [[0,1,2],[1,2,3],[2,3,4],[3,4],[3][]]
    }
}
```

**Comment by devramsean0** [comment]
POST endpoint is redundant and moved to /compile/:code which is urlencoded

**Comment by devramsean0** [comment]
POST AND PUT are now implemented and tested working

**Comment by mr-eggleton** [comment]
Change the return type to be the same as the compile.

**Comment by devramsean0** [comment]
This is implemented and working
